# Generated by Django 4.1.1 on 2022-09-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Note", new_name="Writing",),
    ]
