# Generated by Django 4.1.1 on 2022-09-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_rename_note_writing"),
    ]

    operations = [
        migrations.RenameModel(old_name="Writing", new_name="Note",),
    ]
