# Generated by Django 4.1.1 on 2022-10-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_rename_writing_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note", old_name="auther", new_name="author",
        ),
    ]
